language: node_js

os:
  - linux
  - osx

node_js:
  - 'node'
  - '17'
  - '16'
  - '14'

install:
  - npm install

script:
  - npm run test:ci
  - npm run linter
  - npm run build

cache:
  directories:
    - 'node_modules'
